qcacld-3.0: fix build after disabling debug
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_tx_rx.c:1569:45: error: expected expression
                hdd_debug("LRO and GRO both are disabled");
                                                          ^
1 error generated.

Convert to a normal if-else statement

Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>